language: c

sudo: true

os:
   - linux
   - osx

compiler:
   - gcc
   - clang

before_install:
   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then apt-get update ; fi
   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then apt-get install -y gcc; fi
