language: c

sudo: false

os:
    - osx
    - linux

compiler:
    - gcc
    - clang

script:
    - make
    - make clean

env:
    global:
        - MAKEFLAGS="-j"

branches:
    only:
        - master
