language: c

sudo: true

os:
   - osx
   - linux

compiler:
   - gcc
   - clang

before_install:
   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update ; fi
   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y gcc; fi
   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo gcc --version; fi

script:
   - make
   - make clean
