language: c

os:
    - linux:
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    -g++-7
    - osx

sudo: false

compiler:
    - clang
    - gcc

script:
    - make
    - make clean

env:
    global:
        - MAKEFLAGS="-j"

branches:
    only:
        - master
