language: c

os:
    - linux
    - osx

sudo: false

compiler:
    - clang
    - gcc7

script:
    - make
    - make clean

env:
    global:
        - MAKEFLAGS="-j"

branches:
    only:
        - master
